services:
  - type: web
    name: hermes-render
    runtime: docker
    repo: https://github.com/paxni12345-web/hermes-render
    branch: test-push-branch
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: HERMES_DASHBOARD
        value: "1"
      - key: HERMES_DASHBOARD_HOST
        value: "0.0.0.0"
      - key: HERMES_DASHBOARD_PORT
        value: "10000"
      - key: HERMES_DASHBOARD_BASIC_AUTH_USERNAME
        sync: false
      - key: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
        sync: false
    # CMD ที่จะ override Dockerfile CMD
    dockerCommand: sleep infinity
    healthCheckPath: /api/health
